/**
 * Generated by tsnapi — public API snapshot of `tsdown-kit`
 */
// #region Interfaces
export interface SlugifyOptions {
  readonly separator?: string;
  readonly lowercase?: boolean;
  readonly maxLength?: number;
}
// #endregion

// #region Functions
export declare function slugify(_: string, _?: SlugifyOptions): string;
// #endregion